name: Deploy via SSH

on:
  release:
    types: [published, unpublished, deleted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: bash /app/project/src/scripts/deploy.sh